### ISSUE TITLE
Problem building ZetaCA after moving it

### ISSUE THREAD

**Issue by sstine** [JohnOmernik/zetago#29]
After running this `./zeta cluster sharedldap`, the ZetaCA fails to start wherever it's moved to (where is it moving?)

```
Failed to launch container: Failed to run 'docker -H unix:///var/run/docker.sock pull dockerregv2-shared.marathon.slave.mesos:5005/zetaca:latest': exited with status 1; stderr='Error: image zetaca not found '
```

![image](https://cloud.githubusercontent.com/assets/1295911/22392143/2b65605a-e4ab-11e6-9724-720d9bc16d61.png)

**Comment by JohnOmernik** [comment]
Did you have the shared Docker registry running or did you per chance skip
this?
