### ISSUE TITLE
zeta dcos bootstrap url is 403 forbidden

### ISSUE THREAD

**Issue by ryancmoon** [JohnOmernik/zetago#48]
http://{initial_node_ip}:50091

Shows me 403 forbidden, not sure what the DCOS bootstrap page is supposed to show me.

**Comment by ryancmoon** [comment]
Confirmed on a test fifth run through of the install process today.

**Comment by JohnOmernik** [comment]
It's not supposed to show anything, it's forbidden as it's just a place to download the main binaries for mesos/dcos, and to do that, you need to put in the direct links.  This is desired behaivior.
